### ISSUE TITLE
0.5.3 Release Checklist

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/olsrr#147]
Prepare for release:

* [x] Check that description is informative
* [x] Check licensing of included files
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] `pkgdown::build_site()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] Bump dev version
* [ ] Write blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

Template from <https://github.com/r-lib/usethis/issues/338>
