### ISSUE TITLE
0.6.0 Release Checklist

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/olsrr#189]
* [x] Update vignettes
* [x] Check [current CRAN check results]({cran_results})
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `devtools::build_readme()`
* [x] [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker)
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md`
* [x] Review pkgdown reference index for, e.g., missing topics

Submit to CRAN:

* [x] Bump version in `DESCRIPTION` and `NEWS`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] Tag release
* [x] Bump dev version in `DESCRIPTION` and `NEWS`
* [x] Update install instructions in README
