### ISSUE TITLE
0.5.2 Checklist

### ISSUE THREAD

**Issue by aravindhebbali** [rsquaredacademy/olsrr#99]
Prepare for release:

* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] `pkgdown::build_site()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] Bump dev version

Template from <https://github.com/r-lib/usethis/issues/338>
